name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/Workflow/website
          git stash
          git pull origin master
          npm i
          npm run build:master
          pm2 reload website-master
