name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/website/
          git stash
          git pull origin main
          npm i
          npm run build
