name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/Workflow/website
          git stash
          git pull origin master
          npm i
          npm run build
          pm2 reload website-master
