name: Develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/Workflow/website/develop
          git stash
          git pull origin master
          npm i
          npm run build
          pm2 reload website-develop-serve
