name: Develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/Workflow/website
          git stash
          git pull origin develop
          npm i
          npm run build:develop
          pm2 reload website-develop
